# Generated by Django 5.1.1 on 2024-09-30 03:23

import django.db.models.expressions
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validatorai', '0002_alter_ideavalidation_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='ideavalidation',
            name='user_info',
            field=models.ForeignKey(on_delete=django.db.models.expressions.Case, related_name='user_idea_validation', to=settings.AUTH_USER_MODEL),
        ),
    ]
